//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodCricket.WP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PodCricket.WP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014 copyright by DaVang Solutions.
        /// </summary>
        public static string AbtCopyright {
            get {
                return ResourceManager.GetString("AbtCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by DaVang Solutions.
        /// </summary>
        public static string AbtCreatedBy {
            get {
                return ResourceManager.GetString("AbtCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podcast app for WP.
        /// </summary>
        public static string AbtDescription {
            get {
                return ResourceManager.GetString("AbtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takes the shortest way to your favourite podcasts.
        /// </summary>
        public static string AbtSlogan {
            get {
                return ResourceManager.GetString("AbtSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated on Feb 13 2014.
        /// </summary>
        public static string AbtUpdateDate {
            get {
                return ResourceManager.GetString("AbtUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version 1.1.2.0.
        /// </summary>
        public static string AbtVersion {
            get {
                return ResourceManager.GetString("AbtVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added to download queue.
        /// </summary>
        public static string AddedToDownloadTitle {
            get {
                return ResourceManager.GetString("AddedToDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added to playlist.
        /// </summary>
        public static string AddedToPlayListTitle {
            get {
                return ResourceManager.GetString("AddedToPlayListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to play.
        /// </summary>
        public static string AddToPlayContextMenuTitle {
            get {
                return ResourceManager.GetString("AddToPlayContextMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutTitle {
            get {
                return ResourceManager.GetString("AppBarAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string AppBarDownloadTitlle {
            get {
                return ResourceManager.GetString("AppBarDownloadTitlle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string AppBarHelpTitle {
            get {
                return ResourceManager.GetString("AppBarHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string AppBarPlayTitle {
            get {
                return ResourceManager.GetString("AppBarPlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshTitle {
            get {
                return ResourceManager.GetString("AppBarRefreshTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettingTitle {
            get {
                return ResourceManager.GetString("AppBarSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PodCricket.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure?.
        /// </summary>
        public static string AreYouSureTitle {
            get {
                return ResourceManager.GetString("AreYouSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author.
        /// </summary>
        public static string AuthorTitle {
            get {
                return ResourceManager.GetString("AuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelContextMenuTitle {
            get {
                return ResourceManager.GetString("CancelContextMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto backup.
        /// </summary>
        public static string ConfAutoBackup {
            get {
                return ResourceManager.GetString("ConfAutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to always create a backup to avoid data losing.
        /// </summary>
        public static string ConfAutoBackupDetails {
            get {
                return ResourceManager.GetString("ConfAutoBackupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto queue post.
        /// </summary>
        public static string ConfAutoQueuePost {
            get {
                return ResourceManager.GetString("ConfAutoQueuePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto queue downloaded post to playlist after downloading.
        /// </summary>
        public static string ConfAutoQueuePostDetails {
            get {
                return ResourceManager.GetString("ConfAutoQueuePostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto remove downloaded post.
        /// </summary>
        public static string ConfAutoRemoveDownloadedPost {
            get {
                return ResourceManager.GetString("ConfAutoRemoveDownloadedPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto remove downloaded post from download list.
        /// </summary>
        public static string ConfAutoRemoveDownloadedPostDetails {
            get {
                return ResourceManager.GetString("ConfAutoRemoveDownloadedPostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto resume post.
        /// </summary>
        public static string ConfAutoResumePost {
            get {
                return ResourceManager.GetString("ConfAutoResumePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto resume previous playing postion if you accidentally quit app.
        /// </summary>
        public static string ConfAutoResumePostDetails {
            get {
                return ResourceManager.GetString("ConfAutoResumePostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download with wifi.
        /// </summary>
        public static string ConfDownloadWithWifi {
            get {
                return ResourceManager.GetString("ConfDownloadWithWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just download when wifi connection available.
        /// </summary>
        public static string ConfDownloadWithWifiDetails {
            get {
                return ResourceManager.GetString("ConfDownloadWithWifiDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration.
        /// </summary>
        public static string ConfigurationPageTitle {
            get {
                return ResourceManager.GetString("ConfigurationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keep screen on.
        /// </summary>
        public static string ConfKeepScreenOn {
            get {
                return ResourceManager.GetString("ConfKeepScreenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prevent screen turned off while playing post, this feature just turned on while you are listening.
        /// </summary>
        public static string ConfKeepScreenOnDetails {
            get {
                return ResourceManager.GetString("ConfKeepScreenOnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play post directly in app or use default Windows Phone player.
        /// </summary>
        public static string ConfPlayPostInApDetails {
            get {
                return ResourceManager.GetString("ConfPlayPostInApDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play post in app.
        /// </summary>
        public static string ConfPlayPostInApp {
            get {
                return ResourceManager.GetString("ConfPlayPostInApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show as grid.
        /// </summary>
        public static string ConfShowAsGrid {
            get {
                return ResourceManager.GetString("ConfShowAsGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show subscribed podcasts as grid or list view.
        /// </summary>
        public static string ConfShowAsGridDetails {
            get {
                return ResourceManager.GetString("ConfShowAsGridDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted post.
        /// </summary>
        public static string DeletedDownloadedFile {
            get {
                return ResourceManager.GetString("DeletedDownloadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post not deleted.
        /// </summary>
        public static string ErrCouldNotDeleteStream {
            get {
                return ResourceManager.GetString("ErrCouldNotDeleteStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podcast could not be found.
        /// </summary>
        public static string ErrCouldNotFindPod {
            get {
                return ResourceManager.GetString("ErrCouldNotFindPod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post not found.
        /// </summary>
        public static string ErrCouldNotFindStream {
            get {
                return ResourceManager.GetString("ErrCouldNotFindStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post downloaded but could not be saved.
        /// </summary>
        public static string ErrCouldNotSaveDownloadedStream {
            get {
                return ResourceManager.GetString("ErrCouldNotSaveDownloadedStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there&apos;s an unknown error occured.
        /// </summary>
        public static string ErrGenericError {
            get {
                return ResourceManager.GetString("ErrGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there&apos;s an error while get this podcast.
        /// </summary>
        public static string ErrGetPodError {
            get {
                return ResourceManager.GetString("ErrGetPodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network not found.
        /// </summary>
        public static string ErrNetworkNotAvailable {
            get {
                return ResourceManager.GetString("ErrNetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this podcast was not searched before.
        /// </summary>
        public static string ErrNoOfflineSearchedPodFound {
            get {
                return ResourceManager.GetString("ErrNoOfflineSearchedPodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not search for this podcast.
        /// </summary>
        public static string ErrNoOnlineSearchedPodFound {
            get {
                return ResourceManager.GetString("ErrNoOnlineSearchedPodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there&apos;s no such post in play list.
        /// </summary>
        public static string ErrNoPlayingStreamFound {
            get {
                return ResourceManager.GetString("ErrNoPlayingStreamFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no such podcast subscribed.
        /// </summary>
        public static string ErrNoPodSubscribed {
            get {
                return ResourceManager.GetString("ErrNoPodSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no such post in downloading.
        /// </summary>
        public static string ErrNoStreamDownloadingFound {
            get {
                return ResourceManager.GetString("ErrNoStreamDownloadingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no download link found.
        /// </summary>
        public static string ErrNoStreamDownloadUri {
            get {
                return ResourceManager.GetString("ErrNoStreamDownloadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podcast was not found.
        /// </summary>
        public static string ErrPodPassedInNull {
            get {
                return ResourceManager.GetString("ErrPodPassedInNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this podcast is already subscribed.
        /// </summary>
        public static string ErrPodSubscribed {
            get {
                return ResourceManager.GetString("ErrPodSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you already requested to download this post.
        /// </summary>
        public static string ErrStreamAlreadyInDownloading {
            get {
                return ResourceManager.GetString("ErrStreamAlreadyInDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this post already queued in play list.
        /// </summary>
        public static string ErrStreamAlreadyInPlayingList {
            get {
                return ResourceManager.GetString("ErrStreamAlreadyInPlayingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this post hasn&apos;t been downloaded.
        /// </summary>
        public static string ErrStreamHasNotDownloaded {
            get {
                return ResourceManager.GetString("ErrStreamHasNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres.
        /// </summary>
        public static string GenresTitle {
            get {
                return ResourceManager.GetString("GenresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error while loading, please try again later.
        /// </summary>
        public static string LoadingErrorTitle {
            get {
                return ResourceManager.GetString("LoadingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string LoadingTitle {
            get {
                return ResourceManager.GetString("LoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there&apos;s no post selected to download....
        /// </summary>
        public static string MainPageDownloadStatus {
            get {
                return ResourceManager.GetString("MainPageDownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string MainPageDownloadTitle {
            get {
                return ResourceManager.GetString("MainPageDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string MainPagePauseButtonTitle {
            get {
                return ResourceManager.GetString("MainPagePauseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string MainPagePlayButtonTitle {
            get {
                return ResourceManager.GetString("MainPagePlayButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there&apos;s no post selected to play....
        /// </summary>
        public static string MainPagePlayStatus {
            get {
                return ResourceManager.GetString("MainPagePlayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string MainPagePlayTitle {
            get {
                return ResourceManager.GetString("MainPagePlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MainPageSearchButtonTitle {
            get {
                return ResourceManager.GetString("MainPageSearchButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MainPageSearchTitle {
            get {
                return ResourceManager.GetString("MainPageSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ooops there&apos;s no subscribed pod.
        /// </summary>
        public static string MainPageSubscribedStatus {
            get {
                return ResourceManager.GetString("MainPageSubscribedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribed.
        /// </summary>
        public static string MainPageSubscribedTitle {
            get {
                return ResourceManager.GetString("MainPageSubscribedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track time:.
        /// </summary>
        public static string MainPageTrackTimeTitle {
            get {
                return ResourceManager.GetString("MainPageTrackTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string OpeningTitle {
            get {
                return ResourceManager.GetString("OpeningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podcast.
        /// </summary>
        public static string PodcastDetailsPageTitle {
            get {
                return ResourceManager.GetString("PodcastDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post.
        /// </summary>
        public static string PostDetailsPageTitle {
            get {
                return ResourceManager.GetString("PostDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to published.
        /// </summary>
        public static string PublishedTitle {
            get {
                return ResourceManager.GetString("PublishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app....
        /// </summary>
        public static string RateThisAppTitle {
            get {
                return ResourceManager.GetString("RateThisAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this post was requested to download, do you want to retry?.
        /// </summary>
        public static string ReDownloadTitle {
            get {
                return ResourceManager.GetString("ReDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error while searching, please try again later....
        /// </summary>
        public static string SearchingErrorTitle {
            get {
                return ResourceManager.GetString("SearchingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching....
        /// </summary>
        public static string SearchingTitle {
            get {
                return ResourceManager.GetString("SearchingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streamming....
        /// </summary>
        public static string StreammingTitle {
            get {
                return ResourceManager.GetString("StreammingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribe successfully!.
        /// </summary>
        public static string SubscribeSuccessfullyTitle {
            get {
                return ResourceManager.GetString("SubscribeSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribe.
        /// </summary>
        public static string SubscribeTitle {
            get {
                return ResourceManager.GetString("SubscribeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to download.
        /// </summary>
        public static string ToolkitAddToDownload {
            get {
                return ResourceManager.GetString("ToolkitAddToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to play.
        /// </summary>
        public static string ToolkitAddToPlay {
            get {
                return ResourceManager.GetString("ToolkitAddToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete downloaded file.
        /// </summary>
        public static string ToolkitDeleteDownloadedFile {
            get {
                return ResourceManager.GetString("ToolkitDeleteDownloadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ToolkitRemove {
            get {
                return ResourceManager.GetString("ToolkitRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsubscribe successfully!.
        /// </summary>
        public static string UnsubscribeSuccessfullyTitle {
            get {
                return ResourceManager.GetString("UnsubscribeSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsubscribe.
        /// </summary>
        public static string UnsubscribeTitle {
            get {
                return ResourceManager.GetString("UnsubscribeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string UrlTitle {
            get {
                return ResourceManager.GetString("UrlTitle", resourceCulture);
            }
        }
    }
}
