//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodCricket.WP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PodCricket.WP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PodCricket.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post not deleted.
        /// </summary>
        public static string ErrCouldNotDeleteStream {
            get {
                return ResourceManager.GetString("ErrCouldNotDeleteStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast could not be found.
        /// </summary>
        public static string ErrCouldNotFindPod {
            get {
                return ResourceManager.GetString("ErrCouldNotFindPod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post not found.
        /// </summary>
        public static string ErrCouldNotFindStream {
            get {
                return ResourceManager.GetString("ErrCouldNotFindStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post downloaded but could not be saved.
        /// </summary>
        public static string ErrCouldNotSaveDownloadedStream {
            get {
                return ResourceManager.GetString("ErrCouldNotSaveDownloadedStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s an unknown error occured.
        /// </summary>
        public static string ErrGenericError {
            get {
                return ResourceManager.GetString("ErrGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s an error while get this podcast.
        /// </summary>
        public static string ErrGetPodError {
            get {
                return ResourceManager.GetString("ErrGetPodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network not found.
        /// </summary>
        public static string ErrNetworkNotAvailable {
            get {
                return ResourceManager.GetString("ErrNetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This podcast was not searched before.
        /// </summary>
        public static string ErrNoOfflineSearchedPodFound {
            get {
                return ResourceManager.GetString("ErrNoOfflineSearchedPodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not search for this podcast.
        /// </summary>
        public static string ErrNoOnlineSearchedPodFound {
            get {
                return ResourceManager.GetString("ErrNoOnlineSearchedPodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no such post in play list.
        /// </summary>
        public static string ErrNoPlayingStreamFound {
            get {
                return ResourceManager.GetString("ErrNoPlayingStreamFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such podcast subscribed.
        /// </summary>
        public static string ErrNoPodSubscribed {
            get {
                return ResourceManager.GetString("ErrNoPodSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such post in downloading.
        /// </summary>
        public static string ErrNoStreamDownloadingFound {
            get {
                return ResourceManager.GetString("ErrNoStreamDownloadingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No download link found.
        /// </summary>
        public static string ErrNoStreamDownloadUri {
            get {
                return ResourceManager.GetString("ErrNoStreamDownloadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast was not found.
        /// </summary>
        public static string ErrPodPassedInNull {
            get {
                return ResourceManager.GetString("ErrPodPassedInNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This podcast is already subscribed.
        /// </summary>
        public static string ErrPodSubscribed {
            get {
                return ResourceManager.GetString("ErrPodSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already requested to download this post.
        /// </summary>
        public static string ErrStreamAlreadyInDownloading {
            get {
                return ResourceManager.GetString("ErrStreamAlreadyInDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This post already queued in play list.
        /// </summary>
        public static string ErrStreamAlreadyInPlayingList {
            get {
                return ResourceManager.GetString("ErrStreamAlreadyInPlayingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string MainPageDownloadTitle {
            get {
                return ResourceManager.GetString("MainPageDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string MainPagePlayTitle {
            get {
                return ResourceManager.GetString("MainPagePlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MainPageSearchTitle {
            get {
                return ResourceManager.GetString("MainPageSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribed.
        /// </summary>
        public static string MainPageSubscribedTitle {
            get {
                return ResourceManager.GetString("MainPageSubscribedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast.
        /// </summary>
        public static string PodcastDetailsPageTitle {
            get {
                return ResourceManager.GetString("PodcastDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostDetailsPageTitle {
            get {
                return ResourceManager.GetString("PostDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    }
}
